# Generated by Django 5.0 on 2025-11-12 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_chatroom_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
