# Generated by Django 5.0 on 2025-11-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
