# Generated by Django 5.0 on 2025-11-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0006_alter_item_price_alter_item_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='priority',
        ),
    ]
